### ISSUE TITLE
    ImportError: No module named 'DRU'

### ISSUE THREAD

**Issue by JaspervanSanten** [NVSL/Swoop#9]
Hi,

I am kind of new to github, but i seem to have a problem installing Swoop.
Am i doing something wrong? 
Is the package Ok?

Thanks,

Jasper

(ENVeagle) jasper@Edgy~/GIT/Projects/eagleblib$ pip install Swoop
Collecting Swoop
  Using cached Swoop-0.4.1.tar.gz
Requirement already satisfied: lxml>=3.4.2 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Swoop)
Requirement already satisfied: Sphinx>=1.3.1 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Swoop)
Requirement already satisfied: numpy in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Swoop)
Requirement already satisfied: Jinja2>=2.7.3 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Swoop)
Requirement already satisfied: shapely>=1.5.13 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Swoop)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: Pygments>=2.0 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: docutils>=0.11 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: snowballstemmer>=1.1 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: imagesize in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: setuptools in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: sphinxcontrib-websupport in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: requests>=2.0.0 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: six>=1.5 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Sphinx>=1.3.1->Swoop)
Requirement already satisfied: MarkupSafe>=0.23 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from Jinja2>=2.7.3->Swoop)
Requirement already satisfied: pytz>=0a in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from babel!=2.0,>=1.3->Sphinx>=1.3.1->Swoop)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from requests>=2.0.0->Sphinx>=1.3.1->Swoop)
Requirement already satisfied: idna<2.7,>=2.5 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from requests>=2.0.0->Sphinx>=1.3.1->Swoop)
Requirement already satisfied: certifi>=2017.4.17 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from requests>=2.0.0->Sphinx>=1.3.1->Swoop)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages (from requests>=2.0.0->Sphinx>=1.3.1->Swoop)
Building wheels for collected packages: Swoop
  Running setup.py bdist_wheel for Swoop ... error
  Complete output from command /home/jasper/.virtualenvs/ENVeagle/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ibhfcxxu/Swoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpt2srrov2pip-wheel- --python-tag cp35:
  /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages/setuptools/dist.py:349: UserWarning: Normalizing '0.4.1
  ' to '0.4.1'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-ibhfcxxu/Swoop/setup.py", line 82, in <module>
      cmdclass={'build_py': BuildSwoop}
    File "/home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-ibhfcxxu/Swoop/setup.py", line 17, in run
      import Swoop.GenerateSwoop
    File "/tmp/pip-build-ibhfcxxu/Swoop/Swoop/__init__.py", line 2, in <module>
      from DRU import *
  ImportError: No module named 'DRU'
  
  ----------------------------------------
  Failed building wheel for Swoop
  Running setup.py clean for Swoop
Failed to build Swoop
Installing collected packages: Swoop
  Running setup.py install for Swoop ... error
    Complete output from command /home/jasper/.virtualenvs/ENVeagle/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ibhfcxxu/Swoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ucoea5ob-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jasper/.virtualenvs/ENVeagle/include/site/python3.5/Swoop:
    /home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages/setuptools/dist.py:349: UserWarning: Normalizing '0.4.1
    ' to '0.4.1'
      normalized_version,
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ibhfcxxu/Swoop/setup.py", line 82, in <module>
        cmdclass={'build_py': BuildSwoop}
      File "/home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/jasper/.virtualenvs/ENVeagle/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-ibhfcxxu/Swoop/setup.py", line 17, in run
        import Swoop.GenerateSwoop
      File "/tmp/pip-build-ibhfcxxu/Swoop/Swoop/__init__.py", line 2, in <module>
        from DRU import *
    ImportError: No module named 'DRU'
    
    ----------------------------------------
Command "/home/jasper/.virtualenvs/ENVeagle/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ibhfcxxu/Swoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ucoea5ob-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jasper/.virtualenvs/ENVeagle/include/site/python3.5/Swoop" failed with error code 1 in /tmp/pip-build-ibhfcxxu/Swoop/

**Comment by stevenjswanson** [comment]
Should be resolved now.   Give it a try.

**Comment by stevenjswanson** [comment]
But I haven't pushed the changes to pip, so you need to build from the version in git.  It looks like you are trying to install it from pip.

**Comment by JaspervanSanten** [comment]
Hey Steven,

Thanks a lot for the swift response.
I did try and install it from pip.
I'll try to build it from master tonight.

Cheers,

Jasper

On 6 Dec 2017 6:42 am, "Steven Swanson" <notifications@github.com> wrote:

But I haven't pushed the changes to pip, so you need to build from the
version in git. It looks like you are trying to install it from pip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NVSL/Swoop/issues/9#issuecomment-349540791>, or mute
the thread

**Comment by martonmiklos** [comment]
Hi @stevenjswanson 

I have just tried to install the Swoop with pip3, and got the same error. Is there any way to update the pip package? I think it would be useful for new users.

Thanks in advance!

**Comment by djmerrill** [comment]
I'm still having this issue. Is this package even maintained?!?!

**Comment by stevenjswanson** [comment]
I just pushed my latest version.  Try it.

If it's not, show me how to reproduce.

**Comment by djmerrill** [comment]
> PS C:\Users\Devon\eagle_test> python --version
> Python 3.6.8
> PS C:\Users\Devon\eagle_test> pip install swoop
> Collecting swoop
>   Downloading https://files.pythonhosted.org/packages/58/24/5423722749f8af05c994a40896bcf8ffaa23fc9ed74f118b579cfdffb5f9/Swoop-0.4.1.tar.gz (52kB)
>     100% |████████████████████████████████| 61kB 3.6MB/s
> Requirement already satisfied: lxml>=3.4.2 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from swoop) (4.3.2)
> Requirement already satisfied: Sphinx>=1.3.1 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from swoop) (1.8.4)
> Requirement already satisfied: numpy in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from swoop) (1.16.2)
> Requirement already satisfied: Jinja2>=2.7.3 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from swoop) (2.10)
> Requirement already satisfied: shapely>=1.5.13 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from swoop) (1.6.4.post1)
> Requirement already satisfied: docutils>=0.11 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (0.14)
> Requirement already satisfied: alabaster<0.8,>=0.7 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (0.7.12)
> Requirement already satisfied: colorama>=0.3.5; sys_platform == "win32" in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (0.4.1)
> Requirement already satisfied: setuptools in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (40.6.2)
> Requirement already satisfied: imagesize in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (1.1.0)
> Requirement already satisfied: snowballstemmer>=1.1 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (1.2.1)
> Requirement already satisfied: requests>=2.0.0 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (2.21.0)
> Requirement already satisfied: sphinxcontrib-websupport in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (1.1.0)
> Requirement already satisfied: packaging in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (19.0)
> Requirement already satisfied: Pygments>=2.0 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (2.3.1)
> Requirement already satisfied: babel!=2.0,>=1.3 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (2.6.0)
> Requirement already satisfied: six>=1.5 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Sphinx>=1.3.1->swoop) (1.12.0)
> Requirement already satisfied: MarkupSafe>=0.23 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from Jinja2>=2.7.3->swoop) (1.1.1)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->Sphinx>=1.3.1->swoop) (3.0.4)
> Requirement already satisfied: idna<2.9,>=2.5 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->Sphinx>=1.3.1->swoop) (2.8)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->Sphinx>=1.3.1->swoop) (2018.11.29)
> Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->Sphinx>=1.3.1->swoop) (1.24.1)
> Requirement already satisfied: pyparsing>=2.0.2 in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from packaging->Sphinx>=1.3.1->swoop) (2.3.1)
> Requirement already satisfied: pytz>=0a in c:\users\devon\appdata\local\programs\python\python36\lib\site-packages (from babel!=2.0,>=1.3->Sphinx>=1.3.1->swoop) (2018.9)
> Installing collected packages: swoop
>   Running setup.py install for swoop ... error
>     Complete output from command c:\users\devon\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Devon\\AppData\\Local\\Temp\\pip-install-huv3qt4f\\swoop\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Devon\AppData\Local\Temp\pip-record-vef_sm44\install-record.txt --single-version-externally-managed --compile:
>     c:\users\devon\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py:470: UserWarning: Normalizing '0.4.1
>     ' to '0.4.1'
>       normalized_version,
>     running install
>     running build
>     running build_py
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Devon\AppData\Local\Temp\pip-install-huv3qt4f\swoop\setup.py", line 82, in <module>
>         cmdclass={'build_py': BuildSwoop}
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
>         return distutils.core.setup(**attrs)
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
>         dist.run_commands()
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
>         return orig.install.run(self)
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
>         self.run_command('build')
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "c:\users\devon\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "C:\Users\Devon\AppData\Local\Temp\pip-install-huv3qt4f\swoop\setup.py", line 17, in run
>         import Swoop.GenerateSwoop
>       File "C:\Users\Devon\AppData\Local\Temp\pip-install-huv3qt4f\swoop\Swoop\__init__.py", line 2, in <module>
>         from DRU import *
>     ModuleNotFoundError: No module named 'DRU'
> 
>     ----------------------------------------
> Command "c:\users\devon\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Devon\\AppData\\Local\\Temp\\pip-install-huv3qt4f\\swoop\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Devon\AppData\Local\Temp\pip-record-vef_sm44\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Devon\AppData\Local\Temp\pip-install-huv3qt4f\swoop\
> PS C:\Users\Devon\eagle_test>

**Comment by djmerrill** [comment]
Getting the same error on Windows and Ubuntu.

> user@DESKTOP-TE6QHSS:~$ pip3 install swoop
> Collecting swoop
>   Downloading https://files.pythonhosted.org/packages/58/24/5423722749f8af05c994a40896bcf8ffaa23fc9ed74f118b579cfdffb5f9/Swoop-0.4.1.tar.gz (52kB)
>     100% |████████████████████████████████| 61kB 1.8MB/s
> Collecting Jinja2>=2.7.3 (from swoop)
>   Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
>     100% |████████████████████████████████| 133kB 2.5MB/s
> Collecting Sphinx>=1.3.1 (from swoop)
>   Downloading https://files.pythonhosted.org/packages/75/25/905f901fb749e45cb201f1d946e82f59d84730c430287ea7980b0bcbd2dc/Sphinx-1.8.4-py2.py3-none-any.whl (3.1MB)
>     100% |████████████████████████████████| 3.1MB 471kB/s
> Collecting lxml>=3.4.2 (from swoop)
>   Downloading https://files.pythonhosted.org/packages/79/ae/35f5dbbac8efec8b8d1300858f1ce0b453ea2ff644abe6b5c5c358013dfa/lxml-4.3.2-cp36-cp36m-manylinux1_x86_64.whl (5.7MB)
>     100% |████████████████████████████████| 5.7MB 300kB/s
> Collecting numpy (from swoop)
>   Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
>     100% |████████████████████████████████| 17.3MB 95kB/s
> Collecting shapely>=1.5.13 (from swoop)
>   Downloading https://files.pythonhosted.org/packages/38/b6/b53f19062afd49bb5abd049aeed36f13bf8d57ef8f3fa07a5203531a0252/Shapely-1.6.4.post2-cp36-cp36m-manylinux1_x86_64.whl (1.5MB)
>     100% |████████████████████████████████| 1.5MB 1.1MB/s
> Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.3->swoop)
>   Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
> Collecting setuptools (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (575kB)
>     100% |████████████████████████████████| 583kB 1.8MB/s
> Collecting six>=1.5 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
> Collecting alabaster<0.8,>=0.7 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
> Collecting docutils>=0.11 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
>     100% |████████████████████████████████| 552kB 1.9MB/s
> Collecting requests>=2.0.0 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
>     100% |████████████████████████████████| 61kB 798kB/s
> Collecting babel!=2.0,>=1.3 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl (8.1MB)
>     100% |████████████████████████████████| 8.1MB 210kB/s
> Collecting imagesize (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
> Collecting Pygments>=2.0 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
>     100% |████████████████████████████████| 849kB 1.5MB/s
> Collecting packaging (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
> Collecting snowballstemmer>=1.1 (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
>     100% |████████████████████████████████| 71kB 4.4MB/s
> Collecting sphinxcontrib-websupport (from Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/52/69/3c2fbdc3702358c5b34ee25e387b24838597ef099761fc9a42c166796e8f/sphinxcontrib_websupport-1.1.0-py2.py3-none-any.whl
> Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
>     100% |████████████████████████████████| 143kB 4.3MB/s
> Collecting certifi>=2017.4.17 (from requests>=2.0.0->Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
>     100% |████████████████████████████████| 163kB 3.9MB/s
> Collecting idna<2.9,>=2.5 (from requests>=2.0.0->Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
>     100% |████████████████████████████████| 61kB 3.2MB/s
> Collecting urllib3<1.25,>=1.21.1 (from requests>=2.0.0->Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
>     100% |████████████████████████████████| 122kB 3.0MB/s
> Collecting pytz>=0a (from babel!=2.0,>=1.3->Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
>     100% |████████████████████████████████| 512kB 2.6MB/s
> Collecting pyparsing>=2.0.2 (from packaging->Sphinx>=1.3.1->swoop)
>   Downloading https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl (61kB)
>     100% |████████████████████████████████| 71kB 3.4MB/s
> Building wheels for collected packages: swoop
>   Running setup.py bdist_wheel for swoop ... error
>   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1ent_08b/swoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppkanj_eppip-wheel- --python-tag cp36:
>   /usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '0.4.1
>   ' to '0.4.1'
>     normalized_version,
>   running bdist_wheel
>   running build
>   running build_py
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-build-1ent_08b/swoop/setup.py", line 82, in <module>
>       cmdclass={'build_py': BuildSwoop}
>     File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
>       return distutils.core.setup(**attrs)
>     File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>       self.run_command(cmd)
>     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
>       self.run_command('build')
>     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/tmp/pip-build-1ent_08b/swoop/setup.py", line 17, in run
>       import Swoop.GenerateSwoop
>     File "/tmp/pip-build-1ent_08b/swoop/Swoop/__init__.py", line 2, in <module>
>       from DRU import *
>   ModuleNotFoundError: No module named 'DRU'
> 
>   ----------------------------------------
>   Failed building wheel for swoop
>   Running setup.py clean for swoop
> Failed to build swoop
> Installing collected packages: MarkupSafe, Jinja2, setuptools, six, alabaster, docutils, chardet, certifi, idna, urllib3, requests, pytz, babel, imagesize, Pygments, pyparsing, packaging, snowballstemmer, sphinxcontrib-websupport, Sphinx, lxml, numpy, shapely, swoop
>   Running setup.py install for swoop ... error
>     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1ent_08b/swoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-elama5xa-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
>     /home/user/.local/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.4.1
>     ' to '0.4.1'
>       normalized_version,
>     running install
>     running build
>     running build_py
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-1ent_08b/swoop/setup.py", line 82, in <module>
>         cmdclass={'build_py': BuildSwoop}
>       File "/home/user/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
>         self.run_command('build')
>       File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/tmp/pip-build-1ent_08b/swoop/setup.py", line 17, in run
>         import Swoop.GenerateSwoop
>       File "/tmp/pip-build-1ent_08b/swoop/Swoop/__init__.py", line 2, in <module>
>         from DRU import *
>     ModuleNotFoundError: No module named 'DRU'
> 
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1ent_08b/swoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-elama5xa-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-1ent_08b/swoop/
> user@DESKTOP-TE6QHSS:~$ python3 --version
> Python 3.6.7

**Comment by capaulson** [comment]
Same issue on OS X, both Pip and building from Master both fail. Any update on this?
